### ISSUE TITLE
Delete or keep this app?

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterAppsFreezer/GoogleSignIn#19]
From https://github.com/Starcounter/CompanyTrack/issues/331

Current discussion: 
**Keep?** Having both GoogleSignIn and SignIn shows replaceability of the micro apps. From the point of People it does not matter how you signed in, you can replace SignIn app with any other authorization provider such as GoogleSignIn or your app. 

**Delete?** Has not been touched in a long time and is in a bad condition generally. I don't understand why we have SignIn and GoogleSignIn. It would make more sense to make GoogleSignIn an option in SignIn

@Mackiovello: delete/merge
@Warpech: Keep

Comment by me:
I know @miyconst has an opinion on this one as well. Worth keeping in mind is that GoogleSignIn has been rotting for quite some time and will need some attention to work again. If we're not ready to put the time and energy into that, we're shooting ourselves in the foot by presenting our users with broken apps.

**Comment by warpech** [comment]
Next steps:

- [ ] Make a PR that explains the purpose of this app for future reference.
- [ ] Move this app to https://github.com/StarcounterAppsFreezer. Apps in that organisation do not get updates until we remove them from freezer.

**Comment by warpech** [comment]
Please review https://github.com/StarcounterAppsFreezer/GoogleSignIn/pull/21

**Comment by warpech** [comment]
All done
